In [64]:
import pandas as pd
import json
import ast

In [204]:
Rest_google = pd.read_csv('./Datasets/Restaurantes_Google.csv',delimiter=',')
Rest_google.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Roux's Roadhouse 73,"Roux's Roadhouse 73, 784 WI-73, Nekoosa, WI 54457",0x88008ff5b3c52fd3:0xdbe482cf9fb221db,NaN,44.306954,-89.845783,['Restaurant'],4.2,77,NaN,"[['Thursday', '12–11PM'], ['Friday', '12PM–12A...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 11PM,"['0x88008853d02af353:0x64665a07b4a96dd2', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
1,Crepes n' Tacos Mexican Grill,"Crepes n' Tacos Mexican Grill, suit #5, 5390, ...",0x80c8db636d525e3b:0x6a51cce4b2dcc350,NaN,36.164633,-115.060780,"['Mexican restaurant', 'Crêperie', 'Ice cream ...",4.0,38,NaN,"[['Thursday', '9AM–9PM'], ['Friday', '9AM–9PM'...","{'Service options': ['Delivery'], 'Amenities':...",Permanently closed,"['0x80c8db9d89843609:0x66b93b5ccaec8958', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
2,The Big Eazy,"The Big Eazy, 2053 N Doctor M.L.K. Jr Dr, Milw...",0x8805196ab8890a87:0x837a93dd92ed9d4f,NaN,43.057658,-87.914643,"['Cajun restaurant', 'Creole restaurant']",4.2,108,$$,"[['Thursday', '11AM–10PM'], ['Friday', '11AM–9...","{'Service options': ['Delivery'], 'Amenities':...",Permanently closed,"['0x8805196ab863bab3:0x2466dc0974286f2a', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3,Subway,"Subway, 250 E Wolf Run, Mukwonago, WI 53149",0x8805a2a887bbe777:0xb6c14a56e8897c0f,Casual counter-serve chain for build-your-own ...,42.854168,-88.314247,"['Sandwich shop', 'Caterer', 'Fast food restau...",3.5,26,$,"[['Thursday', 'Closed'], ['Friday', 'Closed'],...","{'Service options': ['Takeout', 'Dine-in'], 'D...",Temporarily closed,"['0x88059800f01c3e33:0xf0107ca9167585bc', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
4,Papa Kelsey's,"Papa Kelsey's, 165 E 1400 N, Logan, UT 84341",0x87547de0ed23364d:0x5b25d19bde61e5d,"Chain eatery serving baked subs, classic pizza...",41.758094,-111.830290,['Pizza restaurant'],4.0,38,$$,"[['Thursday', '11AM–9PM'], ['Friday', '11AM–9P...","{'Service options': ['Delivery'], 'Health & sa...",Permanently closed,"['0x87547dcf5bacaff5:0xd1d5c25dc1f66200', '0x8...",https://www.google.com/maps/place//data=!4m2!3...

In [205]:
Rest_google = Rest_google[['name','address','description','latitude','longitude','category','MISC']]
Rest_google.head()

,name,address,description,latitude,longitude,category,MISC
0,Roux's Roadhouse 73,"Roux's Roadhouse 73, 784 WI-73, Nekoosa, WI 54457",NaN,44.306954,-89.845783,['Restaurant'],"{'Service options': ['Takeout', 'Dine-in', 'De..."
1,Crepes n' Tacos Mexican Grill,"Crepes n' Tacos Mexican Grill, suit #5, 5390, ...",NaN,36.164633,-115.060780,"['Mexican restaurant', 'Crêperie', 'Ice cream ...","{'Service options': ['Delivery'], 'Amenities':..."
2,The Big Eazy,"The Big Eazy, 2053 N Doctor M.L.K. Jr Dr, Milw...",NaN,43.057658,-87.914643,"['Cajun restaurant', 'Creole restaurant']","{'Service options': ['Delivery'], 'Amenities':..."
3,Subway,"Subway, 250 E Wolf Run, Mukwonago, WI 53149",Casual counter-serve chain for build-your-own ...,42.854168,-88.314247,"['Sandwich shop', 'Caterer', 'Fast food restau...","{'Service options': ['Takeout', 'Dine-in'], 'D..."
4,Papa Kelsey's,"Papa Kelsey's, 165 E 1400 N, Logan, UT 84341","Chain eatery serving baked subs, classic pizza...",41.758094,-111.830290,['Pizza restaurant'],"{'Service options': ['Delivery'], 'Health & sa..."

In [223]:
Rest_google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3223 entries, 0 to 3222
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         3223 non-null   object
 1   address      3219 non-null   object
 2   description  1061 non-null   object
 3   latitude     3223 non-null   float64
 4   longitude    3223 non-null   float64
 5   category     3223 non-null   object
 6   MISC         3207 non-null   object
dtypes: float64(2), object(5)
memory usage: 176.4+ KB

In [207]:
Rest_google['category'] = Rest_google['category'].apply(lambda x : eval(x) if x else None)

In [208]:
type(Rest_google['category'][0])

list

In [209]:
Rest_google['MISC'][0]

'{\'Service options\': [\'Takeout\', \'Dine-in\', \'Delivery\'], \'Health & safety\': [\'Staff required to disinfect surfaces between visits\'], \'Highlights\': [\'Great beer selection\', \'Great cocktails\'], \'Popular for\': [\'Lunch\', \'Dinner\', \'Solo dining\'], \'Accessibility\': [\'Wheelchair accessible entrance\'], \'Offerings\': [\'Alcohol\', \'Beer\', \'Cocktails\', \'Coffee\', \'Comfort food\', \'Happy hour food\', \'Hard liquor\', "Kids\' menu", \'Quick bite\', \'Wine\'], \'Amenities\': [\'Bar onsite\', \'Good for kids\', \'High chairs\', \'Restroom\'], \'Atmosphere\': [\'Casual\', \'Cozy\'], \'Crowd\': [\'Groups\', \'Tourists\']}'

In [210]:
texto_corregido = Rest_google['MISC'][0].replace("\'","'")
texto_corregido

'{\'Service options\': [\'Takeout\', \'Dine-in\', \'Delivery\'], \'Health & safety\': [\'Staff required to disinfect surfaces between visits\'], \'Highlights\': [\'Great beer selection\', \'Great cocktails\'], \'Popular for\': [\'Lunch\', \'Dinner\', \'Solo dining\'], \'Accessibility\': [\'Wheelchair accessible entrance\'], \'Offerings\': [\'Alcohol\', \'Beer\', \'Cocktails\', \'Coffee\', \'Comfort food\', \'Happy hour food\', \'Hard liquor\', "Kids\' menu", \'Quick bite\', \'Wine\'], \'Amenities\': [\'Bar onsite\', \'Good for kids\', \'High chairs\', \'Restroom\'], \'Atmosphere\': [\'Casual\', \'Cozy\'], \'Crowd\': [\'Groups\', \'Tourists\']}'

In [211]:
eval(texto_corregido)

{'Service options': ['Takeout', 'Dine-in', 'Delivery'],
 'Health & safety': ['Staff required to disinfect surfaces between visits'],
 'Highlights': ['Great beer selection', 'Great cocktails'],
 'Popular for': ['Lunch', 'Dinner', 'Solo dining'],
 'Accessibility': ['Wheelchair accessible entrance'],
 'Offerings': ['Alcohol',
  'Beer',
  'Cocktails',
  'Coffee',
  'Comfort food',
  'Happy hour food',
  'Hard liquor',
  "Kids' menu",
  'Quick bite',
  'Wine'],
 'Amenities': ['Bar onsite', 'Good for kids', 'High chairs', 'Restroom'],
 'Atmosphere': ['Casual', 'Cozy'],
 'Crowd': ['Groups', 'Tourists']}

In [212]:
Rest_google['MISC'] = Rest_google['MISC'].replace('\'', "'")
Rest_google

,name,address,description,latitude,longitude,category,MISC
0,Roux's Roadhouse 73,"Roux's Roadhouse 73, 784 WI-73, Nekoosa, WI 54457",NaN,44.306954,-89.845783,[Restaurant],"{'Service options': ['Takeout', 'Dine-in', 'De..."
1,Crepes n' Tacos Mexican Grill,"Crepes n' Tacos Mexican Grill, suit #5, 5390, ...",NaN,36.164633,-115.060780,"[Mexican restaurant, Crêperie, Ice cream shop,...","{'Service options': ['Delivery'], 'Amenities':..."
2,The Big Eazy,"The Big Eazy, 2053 N Doctor M.L.K. Jr Dr, Milw...",NaN,43.057658,-87.914643,"[Cajun restaurant, Creole restaurant]","{'Service options': ['Delivery'], 'Amenities':..."
3,Subway,"Subway, 250 E Wolf Run, Mukwonago, WI 53149",Casual counter-serve chain for build-your-own ...,42.854168,-88.314247,"[Sandwich shop, Caterer, Fast food restaurant,...","{'Service options': ['Takeout', 'Dine-in'], 'D..."
4,Papa Kelsey's,"Papa Kelsey's, 165 E 1400 N, Logan, UT 84341","Chain eatery serving baked subs, classic pizza...",41.758094,-111.830290,[Pizza restaurant],"{'Service options': ['Delivery'], 'Health & sa..."
...,...,...,...,...,...,...,...
3218,Thai house - Cotswold Village,"Thai house - Cotswold Village, 110 S Sharon Am...",NaN,35.176453,-80.799708,"[Thai restaurant, Takeout Restaurant, Vegetari...","{'Service options': ['Outdoor seating', 'Curbs..."
3219,King Wok,"King Wok, 7405 Sunset Lake Rd, Fuquay-Varina, ...",NaN,35.595917,-78.774826,"[Chinese restaurant, Asian restaurant]","{'Service options': ['Takeout', 'Delivery', 'D..."
3220,La Chinampa,"La Chinampa, 5442 W Forest Home Ave, Greenfiel...",NaN,42.980399,-87.982667,[Mexican restaurant],"{'Service options': ['Delivery', 'Takeout'], '..."
3221,Maison,"Maison, 5921 W Vliet St, Milwaukee, WI 53208",Modern takes on classic French dishes & premiu...,43.049745,-87.987171,[French restaurant],{'Service options': ['Delivery']}
3222,Bojangles,"Bojangles, 501 S College St, Charlotte, NC 28202",Southern-inspired fast-food chain known for Ca...,35.221936,-80.844894,"[Restaurant, American restaurant, Chicken rest...","{'Service options': ['Takeout', 'Dine-in'], 'H..."

In [222]:
for index,a in enumerate(Rest_google['MISC']):
    if isinstance(a,str):
        Rest_google['MISC'][index] = eval(Rest_google['MISC'][index])

In [230]:
Rest_google.to_parquet('./Datasets/Rest_google.parquet')